name: feature_settings
version: 0.1.0
publish_to: none
environment:
  sdk: ^3.8.0
description: Plan feature package
dependencies:
  firebase_auth: ^5.6.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_sliding_box: ^1.1.5
  freezed_annotation: ^3.0.0
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  hive_ce: ^2.11.3
  hive_ce_generator: ^1.9.2
  intl: any
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  shared:
    path: ../shared
  sliding_box: ^0.0.2
  uuid: ^4.5.1
dev_dependencies:
  build_runner: ^2.5.4
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  http_mock_adapter: any
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  network_image_mock: ^2.1.1
  pubspec_dependency_sorter: ^1.0.5
resolution: workspace
flutter_intl:
  enabled: true
