name: feature_plan
description: Plan feature package
version: 0.1.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  intl: any
  shared:
    path: ../shared

dev_dependencies:
  json_serializable: ^6.9.5
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  freezed: ^3.0.6


flutter:
  generate: true
  uses-material-design: true
